# Generated by Django 4.2.4 on 2023-08-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('user_password', models.CharField(max_length=300, verbose_name='user_password')),
                ('user_id', models.CharField(max_length=64, verbose_name='user_id')),
            ],
            options={
                'db_table': 'polls',
            },
        ),
    ]
