# Generated by Django 4.2.4 on 2023-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postname',
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(max_length=50),
        ),
    ]
